CREATE DATABASE IF NOT EXISTS rosweb;

CREATE TABLE IF NOT EXISTS rosweb.logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  level ENUM('INFO','WARN','ERROR') DEFAULT 'INFO',
  event VARCHAR(64) NOT NULL,
  detail TEXT
);

CREATE INDEX idx_logs_ts ON rosweb.logs (ts);
