CREATE DATABASE IF NOT EXISTS ros_logs CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE ros_logs;
CREATE TABLE IF NOT EXISTS logs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  action VARCHAR(64),
  state  VARCHAR(64),
  status VARCHAR(64),
  details TEXT
);
