CREATE DATABASE IF NOT EXISTS ros_logs;

USE ros_logs;

CREATE TABLE IF NOT EXISTS logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  level ENUM('INFO','WARN','ERROR') DEFAULT 'INFO',
  event VARCHAR(64) NOT NULL,
  detail TEXT
);

CREATE INDEX idx_logs_ts ON logs (ts);
